services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  annotation.reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    calls:
      - method: addGlobalIgnoredName
        arguments:
          - 'required'
          # dummy arg to register class_exists as annotation loader only when required
          - '@Doctrine\Common\Annotations\AnnotationRegistry'

  Doctrine\Common\Annotations\AnnotationRegistry:
    calls:
      - method: registerLoader
        arguments:
         - class_exists
