services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  annotation.reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    calls:
      - method: addGlobalIgnoredName
        arguments:
          - 'required'


  Doctrine\Common\Annotations\AnnotationReader:
    alias : annotation.reader