services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  service_container:
    class: Symfony\Component\DependencyInjection\ContainerBuilder

  Symfony\Component\HttpFoundation\ParameterBag: ~
