services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Symfony\Component\EventDispatcher\EventDispatcher:
    alias : event_dispatcher