services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  TelNowEdge\FreePBX\Base\Logger\LoggerFactory:
    arguments:
      $ampConfManager: '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  logger:
    class: TelNowEdge\FreePBX\Base\Logger\Logger
    factory: ['@TelNowEdge\FreePBX\Base\Logger\LoggerFactory', 'createLogger']

  TelNowEdge\FreePBX\Base\Logger\Logger:
    alias: logger