services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  request_stack:
    class: Symfony\Component\HttpFoundation\RequestStack
    calls:
      - method: push
        arguments:
          - '@request'

  request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['Symfony\Component\HttpFoundation\Request', createFromGlobals]
    calls:
      - method: setSession
        arguments:
          - '@session'

  Symfony\Component\HttpFoundation\Request:
    alias: 'request'

  Symfony\Component\HttpFoundation\RequestStack:
    alias: 'request_stack'
