services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  security.csrf.token_generator:
    class: Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator

  Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface:
    alias: security.csrf.token_generator

  # request_stack:
  #   class: Symfony\Component\HttpFoundation\RequestStack
  #   calls:
  #     - method: push
  #       arguments:
  #         - '@request'
  # TODO : la request_stack est appelée mais le push n'est pas fait
  security.csrf.token_storage:
    class: Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage
    arguments:
      - '@request_stack'

  Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface:
    alias: security.csrf.token_storage

  security.csrf.token_manager:
    class: Symfony\Component\Security\Csrf\CsrfTokenManager
    arguments:
      - '@security.csrf.token_generator'
      - '@security.csrf.token_storage'
      - '@request_stack'
