services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  Symfony\Component\Serializer\Encoder\JsonEncoder: ~

  TelNowEdge\FreePBX\Base\Serializer\Normalizer\ObjectNormalizerFactory: ~

  object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    factory: [ '@TelNowEdge\FreePBX\Base\Serializer\Normalizer\ObjectNormalizerFactory', 'getObjectNormalizer' ]

  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    alias: object_normalizer

  Symfony\Component\Serializer\Serializer:
    arguments:
      - ['@Symfony\Component\Serializer\Normalizer\ObjectNormalizer']
      - ['@Symfony\Component\Serializer\Encoder\JsonEncoder']

  serializer:
    alias: Symfony\Component\Serializer\Serializer
