services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Asterisk *************************************************************
  TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory: ~

  AsteriskManager:
    class: AGI_AsteriskManager
    factory: [ '@TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory', 'getAsteriskManager' ]

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  AGI_AsteriskManager:
    alias: AsteriskManager

  # Repositories *************************************************************
  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'
          - '@addons_connection'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Repository\AbstractAsteriskRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
          - '@asterisk_connection'

  TelNowEdge\FreePBX\Base\Repository\AbstractFileSystemRepository:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  TelNowEdge\FreePBX\Base\Repository\AbstractLdapRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  # DialPlans *************************************************************
  TelNowEdge\FreePBX\Base\DialPlan\Generator\AbstractGenerator:
    abstract: true

  TelNowEdge\FreePBX\Base\DialPlan\File\AbstractFile:
    abstract: true

  #Handlers *************************************************************
  TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'
          - '@addons_connection'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractAstHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractFileSystemHandler:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractLdapHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  #Constraints ***************************************************
#  validators:
#    namespace: TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\
#    resource: '/devel/freepbx-base/Validator/Constraints/*Validator'
#    calls:
#      - method: setContainer
#        arguments:
#          - '@service_container'
#    tags: [ validator.constraint_validator ]

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  TelNowEdge\FreePBX\Base\Validator\Constraints\DependsValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  TelNowEdge\FreePBX\Base\Validator\Constraints\UniqueIdValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  TelNowEdge\FreePBX\Base\Validator\Constraints\CompoundUniqueValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  TelNowEdge\FreePBX\Base\Validator\Constraints\ValidExtensionValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  # Migrations *************************************************************
  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractPhpMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    calls:
      - method: setApplication
        arguments:
          - '@freepbx_application'

  # Controller *************************************************************
  TelNowEdge\FreePBX\Base\Controller\AbstractController:
    abstract: true
    calls:
      - method: setRequest
        arguments:
          - '@request'
      - method: setContainer
        arguments:
          - '@service_container'
  # Forms *************************************************************
  TelNowEdge\FreePBX\Base\Form\DestinationType:
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Form\RepositoryType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  # Helper *************************************************************
  TelNowEdge\FreePBX\Base\Helper\DestinationHelper: ~

  # Managers *************************************************************
  TelNowEdge\FreePBX\Base\Manager\AmpConfManager: ~

  memcached_default_connection:
    class: Memcached
    factory: [ '@TelNowEdge\FreePBX\Base\Manager\MemcachedFactory', 'createMemcachedManager' ]
    arguments:
      - 'default'

  TelNowEdge\FreePBX\Base\Manager\MemcachedFactory: ~

  TelNowEdge\FreePBX\Base\Manager\ManagerFactory:
    calls:
      - method: setUserEventManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\UserEventManager'
      - method: setHintManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\HintManager'

  # Managers *************************************************************

  TelNowEdge\FreePBX\Base\Manager\UserEventManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Manager\HintManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Manager\SipNotifyManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Manager\DevStateManager: ~

  TelNowEdge\FreePBX\Base\Manager\SendRequestManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  # Consoles *************************************************************
  TelNowEdge\FreePBX\Base\Console\ApplicationFactory: ~

  freepbx_application:
    class: Symfony\Component\Console\Application
    factory: [ '@TelNowEdge\FreePBX\Base\Console\ApplicationFactory', 'createApplication' ]

  #Dotrine ***************************************************************
  Doctrine\Common\Collections\ArrayCollection : ~

  # Globals *************************************************************
  controllers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Controller/'
    parent: TelNowEdge\FreePBX\Base\Controller\AbstractController
    tags:
      - "telnowedge.controller"

  repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository

  simple_repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/Simple/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository

  notmapped_repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/NotMapped/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository

  asterisk_repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/Asterisk/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractAsteriskRepository

  ldap_repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/Ldap/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractLdapRepository

  filesystem_repositories:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Repository/FileSystem/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractFileSystemRepository

  db_handlers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Handler/DbHandler/'
    parent: TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler

  ast_handlers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Handler/AstHandler/'
    parent: TelNowEdge\FreePBX\Base\Handler\AbstractAstHandler

  fileSystem_handlers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Handler/FileSystemHandler/'
    parent: TelNowEdge\FreePBX\Base\Handler\AbstractFileSystemHandler

  ldap_handlers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Handler/LdapHandler/'
    parent: TelNowEdge\FreePBX\Base\Handler\AbstractLdapHandler

  managers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Manager/'

  providers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Provider/'

  helpers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Helpers/'

  helper:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Helper/'

  wrappers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Wrapper/'

  sql_migrations:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Resources/Migrations/SqlMigrations/'
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration

  php_migrations:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Resources/Migrations/PhpMigrations/'
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractPhpMigration

  event_subscribers:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/EventSubscriber/'
    tags:
      - "kernel.event_subscriber"

  generator_dialPlans:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/DialPlan/Generator/'
    parent: TelNowEdge\FreePBX\Base\DialPlan\Generator\AbstractGenerator

  file_dialPlans:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/DialPlan/File/'
    parent: TelNowEdge\FreePBX\Base\DialPlan\File\AbstractFile

  forms:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Form/'
    tags:
      - "form.type"

  utils:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Util/'


  modules_validators:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Validator/Constraints/*Validator.php'
    tags: [validator.constraint_validator]

  models:
    namespace: TelNowEdge\Module\
    resource: '%freepbx.root_dir%/../../../../../../modules/*/Model'
