services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    arguments:
      - 'ddss'
    tags: [validator.constraint_validator]

  validator.validator_factory:
    class: Symfony\Component\Validator\ContainerConstraintValidatorFactory
    arguments:
      -

  validator.expression:
    class: Symfony\Component\Validator\Constraints\ExpressionValidator
    tags:
      - {name:validator.constraint_validator, alias:validator.expression}

  validator.email:
    class: Symfony\Component\Validator\Constraints\EmailValidator
    tags:
      - {name:validator.constraint_validator, alias:Symfony\Component\Validator\Constraints\EmailValidator}
    arguments: ~
