services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    arguments:
      - 'ddss'
    tags: [validator.constraint_validator]
