services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  # Asterisk *************************************************************
  TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory: ~

  AsteriskManager:
    class: AGI_AsteriskManager
    factory: [ '@TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory', 'getAsteriskManager' ]

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  # Repositories *************************************************************
  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'
          - '@addons_connection'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Repository\AbstractAsteriskRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
          - '@asterisk_connection'

  TelNowEdge\FreePBX\Base\Repository\AbstractFileSystemRepository:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  TelNowEdge\FreePBX\Base\Repository\AbstractLdapRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  # DialPlans *************************************************************
  TelNowEdge\FreePBX\Base\DialPlan\Generator\AbstractGenerator:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\DialPlan\File\AbstractFile:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  #Handlers *************************************************************
  TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'
          - '@addons_connection'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractAstHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractFileSystemHandler:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractLdapHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  #Constraints ***************************************************
  validators:
    namespace: TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\
    resource: '/devel/freepbx-base/Validator/Constraints/Validators/*'
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [ validator.constraint_validator ]

  #  TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\ChoiceValidator:
  #    calls:
  #      - method: setContainer
  #        arguments:
  #          - '@service_container'
  #    tags: [ validator.constraint_validator ]
  #
  #  TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\DependsValidator:
  #    calls:
  #      - method: setContainer
  #        arguments:
  #          - '@service_container'
  #    tags: [ validator.constraint_validator ]
  #
  #  TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\UniqueIdValidator:
  #    calls:
  #      - method: setContainer
  #        arguments:
  #          - '@service_container'
  #    tags: [ validator.constraint_validator ]
  #
  #  TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\CompoundUniqueValidator:
  #    calls:
  #      - method: setContainer
  #        arguments:
  #          - '@service_container'
  #    tags: [ validator.constraint_validator ]
  #
  #  TelNowEdge\FreePBX\Base\Validator\Constraints\Validators\ValidExtensionValidator:
  #    calls:
  #      - method: setContainer
  #        arguments:
  #          - '@service_container'
  #    tags: [ validator.constraint_validator ]

  # Migrations *************************************************************
  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration:
    abstract: true
    arguments:
      $annotationReader: '@annotation.reader'
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractPhpMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    calls:
      - method: setApplication
        arguments:
          - '@freepbx_application'

  # Controller *************************************************************
  TelNowEdge\FreePBX\Base\Controller\AbstractController:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
      - method: setRequest
        arguments:
          - '@request'

  # Forms *************************************************************
  TelNowEdge\FreePBX\Base\Form\DestinationType:
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Form\RepositoryType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  # Helper *************************************************************
  TelNowEdge\FreePBX\Base\Helper\DestinationHelper: ~

  # Managers *************************************************************
  TelNowEdge\FreePBX\Base\Manager\AmpConfManager: ~

  memcached_default_connection:
    class: Memcached
    factory: [ '@TelNowEdge\FreePBX\Base\Manager\MemcachedFactory', 'createMemcachedManager' ]
    arguments:
      - 'default'

  TelNowEdge\FreePBX\Base\Manager\MemcachedFactory: ~

  TelNowEdge\FreePBX\Base\Manager\ManagerFactory:
    calls:
      - method: setUserEventManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\UserEventManager'
      - method: setHintManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\HintManager'

  # Managers *************************************************************
  TelNowEdge\FreePBX\Base\Manager\:
    resource: '../../Manager/'
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
    exclude:
      - '../../Manager/AmpConfManager.php'
      - '../../Manager/AsteriskManagerFactory.php'
      - '../../Manager/ManagerFactory.php'
      - '../../Manager/MemcachedFactory.php'

  #  TelNowEdge\FreePBX\Base\Manager\UserEventManager:
  #    calls:
  #      - method: setConnection
  #        arguments:
  #          - '@AsteriskManager'
  #
  #  TelNowEdge\FreePBX\Base\Manager\HintManager:
  #    calls:
  #      - method: setConnection
  #        arguments:
  #          - '@AsteriskManager'
  #
  #  TelNowEdge\FreePBX\Base\Manager\SipNotifyManager:
  #    calls:
  #      - method: setConnection
  #        arguments:
  #          - '@AsteriskManager'
  #
  #  TelNowEdge\FreePBX\Base\Manager\DevStateManager:
  #    calls:
  #      - method: setConnection
  #        arguments:
  #          - '@AsteriskManager'
  #
  #  TelNowEdge\FreePBX\Base\Manager\SendRequestManager:
  #    calls:
  #      - method: setConnection
  #        arguments:
  #          - '@AsteriskManager'

  # Consoles *************************************************************
  TelNowEdge\FreePBX\Base\Console\ApplicationFactory: ~

  freepbx_application:
    class: Symfony\Component\Console\Application
    factory: [ '@TelNowEdge\FreePBX\Base\Console\ApplicationFactory', 'createApplication' ]

  # Globals *************************************************************
  controllers:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/Controller/'
    parent: TelNowEdge\FreePBX\Base\Controller\AbstractController
    tags:
      - "telnowedge.controller"

  repositories:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/Repository/'
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository

  handlers:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/Handler/'
    parent: TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler

  managers:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/Manager/'

  migrations:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/Resources/Migrations/'
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration

  event_subscriber:
    namespace: TelNowEdge\Module\
    resource: '/../../../var/www/admin/modules/*/EventSubscriber/'
    tags:
      - "kernel.event_subscriber"