services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory: ~

  AsteriskManager:
    class: AGI_AsteriskManager
    factory: 'TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory:getAsteriskManager'

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'

  TelNowEdge\FreePBX\Base\Repository\AbstractAsteriskRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Repository\AbstractFileSystemRepository:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  TelNowEdge\FreePBX\Base\Repository\AbstractLdapRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'

  TelNowEdge\FreePBX\Base\DialPlan\Generator\AbstractGenerator:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\DialPlan\File\AbstractFile:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractAstHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractFileSystemHandler:
    abstract: true
    calls:
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractLdapHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@ldap_default_connection'
      - method: setAmpConfManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\AmpConfManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\DependsValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\UniqueIdValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\CompoundUniqueValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\ValidExtensionValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration:
    abstract: true
    arguments:
      $annotationReader: '@annotation.reader'
    calls:
      - method: setConnection
        arguments:
          - '@default_connection'
          - '@cdr_connection'

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractPhpMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Controller\AbstractController:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\Form\DestinationType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Form\RepositoryType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Helper\DestinationHelper: ~

  TelNowEdge\FreePBX\Base\Manager\AmpConfManager: ~

  TelNowEdge\FreePBX\Base\Manager\ManagerFactory:
    calls:
      - method: setUserEventManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\UserEventManager'
      - method: setHintManager
        arguments:
          - '@TelNowEdge\FreePBX\Base\Manager\HintManager'

  TelNowEdge\FreePBX\Base\Manager\UserEventManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Manager\HintManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\Manager\SipNotifyManager:
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
