services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory: ~

  AsteriskManager:
    class: AGI_AsteriskManager
    factory: 'TelNowEdge\FreePBX\Base\Manager\AsteriskManagerFactory:getAsteriskManager'

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Repository\AbstractAsteriskRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'

  TelNowEdge\FreePBX\Base\DialPlan\Generator\AbstractGenerator:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Handler\AbstractAstHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@AsteriskManager'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\DependsValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\UniqueIdValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\ValidExtensionValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractSqlMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractPhpMigration:
    abstract: true
    parent: TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\FreePBX\Base\Controller\AbstractController:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\Form\DestinationType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Form\RepositoryType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Helper\DestinationHelper: ~

  TelNowEdge\FreePBX\Base\Manager\AmpConfManager: ~
