services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  FreePBX\Database:
    arguments:
      - 'mysql:host=localhost;dbname=asterisk;charset=utf8'

  TelNowEdge\FreePBX\Base\Repository\AbstractRepository:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Handler\AbstractDbHandler:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'
      - method: setEventDispatcher
        arguments:
          - '@event_dispatcher'

  TelNowEdge\FreePBX\Base\Validator\Constraints\ChoiceValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Validator\Constraints\DependsValidator:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: [validator.constraint_validator]

  TelNowEdge\FreePBX\Base\Resources\Migrations\AbstractMigration:
    abstract: true
    calls:
      - method: setConnection
        arguments:
          - '@FreePBX\Database'

  TelNowEdge\FreePBX\Base\Controller\AbstractController:
    abstract: true
    calls:
      - method: setContainer
        arguments:
          - '@service_container'

  TelNowEdge\FreePBX\Base\Form\DestinationType:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "form.type"

  TelNowEdge\FreePBX\Base\Helper\DestinationHelper: ~
