services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  template_engine:
    class: TelNowEdge\FreePBX\Base\Template\TemplateEngine
    arguments:
      - '@security.csrf.token_manager'

  twig:
    class: Twig\Environment
    factory: [ '@template_engine', 'getTemplateEngine' ]

  Twig\Environment :
    alias : twig
