services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  validator:
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: [ '@validator.builder', 'getValidator' ]

  Symfony\Component\Validator\Validator\ValidatorInterface:
    alias: validator

  validator.builder:
    class: Symfony\Component\Validator\ValidatorBuilder
    factory: ['Symfony\Component\Validator\Validation', createValidatorBuilder]
    calls:
      - method: enableAnnotationMapping
        arguments:
          - '@annotation.reader'
      - method: setConstraintValidatorFactory
        arguments:
          - '@validator.validator_factory'

  validator.validator_factory:
    class: Symfony\Component\Validator\ContainerConstraintValidatorFactory
    arguments:
      # Argument must be present but he is replaced by compiler pass AddConstraintValidatorsPass()
      -

  validator.expression:
    class: Symfony\Component\Validator\Constraints\ExpressionValidator
    tags:
      - { name: validator.constraint_validator, alias: validator.expression }

  validator.email:
    class: Symfony\Component\Validator\Constraints\EmailValidator
    tags:
      - { name: validator.constraint_validator, alias: Symfony\Component\Validator\Constraints\EmailValidator }
    arguments: ~
